data/nodeinfo.go
This will omit nil values for longitude and latitude in location.
Without this a nil value will be represented as 0 which is a valid value to meshviewer and the node is displayed at a wrong position.
=> [BUGFIX] omit longitude and latitude in location if empty

data/airtime.go, data/airtime_test.go
=> Fix airtime calculation

config_example.toml, database/influxdb/database.go, database/influxdb/database_test.go
This patch adds the posibility, to add an additional tag (called `job`) to influx data. This may be helpful if you are running multiple sites .
=> [TASK] add job tag to influxdb database type

database/influxdb/database.go
Fatal() calls os.Exit(1), which causes yanic.service to fail if database is not reachable.
=> [RFC] influxdb: replace log.Fatal() by log.Print()

database/graphite/global.go, database/graphite/node.go, database/graphite/utils.go
Fixes naming and compatibility with meshviewer ([yanic:database/graphite/node.go](https://github.com/FreifunkBremen/yanic/blob/88975d256609a4674508afd6c53ca8d317573b90/database/graphite/node.go#L28) vs [meshviewer:lib/infobox/node.js](https://github.com/ffrgb/meshviewer/blob/ecf73dd7ab3c717524b06cad8c5b6d7191a192ff/lib/infobox/node.js#L175)) and with Graphite
=> [BUGFIX] Fixed Graphite naming

cmd/yanic/main.go, data/nodeinfo.go, database/all/internal.go, database/database.go, database/graphite/database.go, database/graphite/link.go, database/influxdb/database.go, database/influxdb/link.go, database/influxdb/node.go, database/influxdb/node_test.go, database/logging/file.go, meshviewer/graph.go, meshviewer/graph_test.go, respond/collector.go, runtime/node.go, runtime/nodes.go, runtime/nodes_test.go
=> [TASK] add per-link statistics to influxdb

contrib/yanic-remove-node
I was fiddling with multidomain stuff and moved nodes between domains which caused duplicate nodeids in each domain, which meshviewer currently doesn't handle well.
Removing a node by hand is more than cumbersome, so a small script was needed. Not much, but sure worth sharing.
```
```
Prints a message if the node was
- removed
- not found
=> [TASK] Add script to remove nodes by nodeid

database/influxdb/node.go, database/influxdb/node_test.go
As Yanic now support multiple meshes in one instance it would be handy to have the _site_code_ as tag in the _node_ measurement. As I don't see a reason to also include the _site_name_ I shortened the tag name to _site_.
=> [TASK] influxdb: add site tag to node

cmd/import.go, cmd/query.go, cmd/serve.go, config_example.toml, database/all/internal.go, database/database.go, database/graphite/database.go, database/graphite/global.go, database/influxdb/global.go, database/influxdb/global_test.go, database/logging/file.go, respond/collector.go, respond/collector_test.go, runtime/config.go, runtime/stats.go, runtime/stats_test.go
As suggested in #98 this adds global statistics per configured site.
The sites for which individual statistics are created can be specified in the config and if the list is empty only the already existing global statistic is created.
```
[respondd]
sites = ["ffwi","ffmz"]
```
Site specific and global statistics are stored in different measurements. For _influxdb_ site specific data is stored inside `(global|firmware|model|autoupdater)_site` with tag `site=$sitecode`. As _graphite_ doesn't support tags (yet) one measurement `(global|firmware|model)_$sitecode` is created for each configured site.
Example output could be viewed under https://stats.freifunk-mwu.de/dashboard/db/freifunk-mwu-test
=> [TASK] add global statistics for individual sites

output/meshviewer-ffrgb/meshviewer.go, output/meshviewer/graph.go
https://github.com/ffnord/mesh-announce/issues/25
=> [BUGFIX] fix link type detection by different sources

database/graphite/node.go, database/influxdb/node.go
=> [TASK] add nproc to database

cmd/config_test.go, cmd/import.go, cmd/query.go, cmd/serve.go, config_example.toml, data/nodeinfo.go, database/all/connection.go, database/database.go, database/graphite/global.go, database/influxdb/global.go, database/influxdb/global_test.go, database/influxdb/node.go, database/influxdb/node_test.go, database/logging/file.go, database/logging/file_test.go, database/respondd/main.go, docs/docs_configuration.md, output/all/filter.go, output/filter/domainappendsite/domainappendsite.go, output/filter/domainappendsite/domainappendsite_test.go, output/filter/domainassite/domainassite.go, output/filter/domainassite/domainassite_test.go, output/meshviewer-ffrgb/struct.go, respond/collector.go, respond/collector_test.go, respond/config.go, respond/config_test.go, runtime/stats.go, runtime/stats_test.go
fix #82 
- in database
- filter for ease use old software (after #114)
=> [TASK] handle domain_code

cmd/config_test.go, cmd/query.go, cmd/serve.go, config_example.toml, data/neighbours.go, data/nodeinfo.go, data/nodeinfo_test.go, database/influxdb/link.go, database/influxdb/node_test.go, docs/docs_configuration.md, docs/docs_quick_conf.md, docs/home_about.md, output/meshviewer-ffrgb/meshviewer.go, output/meshviewer-ffrgb/meshviewer_test.go, output/meshviewer-ffrgb/struct.go, respond/collector.go, respond/collector_test.go, respond/config.go, respond/respond.go, runtime/node.go, runtime/nodes.go, runtime/nodes_test.go
fixed #70 
Network running with [gluon](https://github.com/FreifunkBremen/gluon-site-ffhb/tree/babel) from [fffm christf_next](https://github.com/freifunk-ffm/gluon/tree/christf_next) branch
On VPN05 with [ansible](https://github.com/FreifunkBremen/ansible/tree/babel)
=> [TASK] Add support for babel

output/meshviewer-ffrgb/struct.go, output/meshviewer-ffrgb/struct_test.go
- Export a `nil` / `null` produced an error at meshviewer-ffrgb
=> [BUGFIX] meshviewer-ffrgb export empty array

cmd/config_test.go, config_example.toml, docs/docs_configuration.md, output/all/main.go, output/geojson/geojson.go, output/geojson/geojson_test.go, output/geojson/output.go, output/geojson/output_test.go
Adds output of nodes.geojson which contains points of all nodes which share their location.
To be able to design zones where the nodes should be part of I wanted to export the nodes as a geojson as input.
As [uMap](https://umap.openstreetmap.fr) supports adding a "remote layer" which takes a geojson as input I tried to implement an interface to let this geojson be automatically rendered.
=> [TASK] Add output for nodes.geojson

docs/docs_configuration.md, output/all/main.go, output/raw/output.go, output/raw/raw.go, output/raw/raw_test.go
Add a output format which just passes the raw data as received by
respondd, i.e. in sections "statistics", "nodeinfo" and "neighbours".
We use data from respondd to segment our network. It is therefore important for us
to get all information.
=> add raw output support

Gopkg.toml, cmd/query.go, cmd/serve.go, config_example.toml, data/response.go, docs/docs_configuration.md, output/filter/noowner/noowner.go, output/meshviewer-ffrgb/struct.go, output/meshviewer-ffrgb/struct_test.go, output/raw/raw.go, respond/collector.go, respond/collector_test.go, respond/config.go, runtime/node.go, runtime/nodes.go
This commit allows to define custom fields in the configuration file, which
will cause Yanic to also save the values of these custom fields in its internal
data structures. Output modules can then decide whether they want to include
these fields. For most cases, this should avoid the need for patches in Yanic.
At the moment, if one has a custom respondd module which includes custom
fields, Yanic will simply ignore these fields. Communities which have custom
fields have to maintain patches on Yanic to have them available.
=> [TASK] Add support for custom respondd fields

database/influxdb/link.go, runtime/node.go, runtime/nodes.go
This adds the additional tags source.hostname and target.hostname to the influx link measurements.
Grafana is currently not able to resolve the target.id or source.id into a human readable hostname. Therefore reading the neighbour graphs is quite difficult for humans. This is resolved by adding the additional tags source.hostname and target.hostname as suggested here.
With this change, we can build a graph like this:
This is just a very first draft, which probably needs some more var != nil checks or so. It's intended as a basis for discussion.
My Questions:
- Would you accept this feature in general?
- What do I have to change in the code to get this accepted?
- Especially:
- Which of the variables used do I need to check if they are `nil`? Is `nodes.List[neighbours.NodeID]` always …
=> Add source.hostname/target.hostname to influx output

docs/docs_configuration.md, output/all/main.go, output/raw-jsonl/output.go, output/raw-jsonl/output_test.go, output/raw-jsonl/raw_jsonl.go, output/raw-jsonl/raw_jsonl_test.go, runtime/node.go, runtime/nodes.go
This output takes the respondd response as sent by the node and includes
it in a Line-Delimited JSON (JSONL) document. In this format each line
can be interpreted as separate JSON element, which is useful for json
streaming. The first line is json object holding the timestamp and
version of the file. Then there follows one line for each node, each
containing a json object.
An example output looks like this:
{"version":1,"updated_at":"2021-03-27T21:58:48+0100","format":"raw-nodes-jsonl"}
{"firstseen": ..., "lastseen": ..., "online":true, "statistics": {...}, "nodeinfo": {...}, "neighbours":null, "custom_fields":null}
{"firstseen": ..., "lastseen": ..., "online":true, "statistics": {...}, "nodeinfo": {...}, "neighbours":null, "custom_fields":null}
{"firstseen": ..., "lastseen": ..., …
=> [TASK] add output raw-jsonl

runtime/nodes.go
Before this commit, the value of target.hostname was incorrect.
It was accidentially pointing to the hostname of the source of
the link. This means target.hostname was equal to source.hostname.
Fixes: #197
Fixes: 0325aad24e1cd762c8e7204fa016d4d007a4419d
=> [BUG] fix target.hostname of links

README.md
Previously it said FF Nord was using yanic+Hopglass and FF Kiel was using yanic+ffrgb/Meshviewer, but actually FF Nord is using ffrgb/meshviewer and FF Kiel is not using yanic at all as can be seen by the /raw.json and /metrics API endpoints.
=> [DOC] Fix "Communities using Yanic" info in README

data/nodeinfo.go, data/testdata/nodeinfo.json
This implements basic support for WireGuard in accordance of the fastd-related paragraphs in code.
We, @freifunkh are currently building up our WireGuard infrastructure;
and giving back something to yanic after using it for years seemed appropriate.
Furthermore this resolves #183 and could bring new momentum to the discussion of #66.
I do not think fastd is documented either; so I'm unsure whether this is matter to document, or not.
replaces #187 in order to use correct branches
=> [TASK] add WireGuard

.circleci/check-testfiles, go.mod, go.sum, respond/collector.go
Set IPV6_MULTICAST_IF on the collector's UDP socket, so the correct outgoing interface is chosen when a non-link-local bind address is configured.
Closes #167
=> [BUGFIX] Set IPV6_MULTICAST_IF for correct interface selection

config_example.toml
Add a comment that it's possible to have a `respondd.interfaces` section for different multicast addresses to work with old and new gluon nodes on the same network.
On our freifunk network are some nodes that multicast to ff02, some that multicast to ff05 and some intermediate versions that multicast to both. I added a hint to the docs how to configure the map to support both.
- (no code changes)
=> [DOC] Explain how to receive old and new gluon nodes

cmd/config_test.go, config_example.toml, docs/docs_configuration.md, output/all/main.go, output/prometheus-sd/output.go, output/prometheus-sd/output_test.go
make smaller PR of #189 to easier merge.
create a json for prometheus service discovery e.g. for usage in ping blackbox-exporter
=> [TASK] add output prometheus-sd (service discovery)

database/influxdb/database.go
Freifunk München experiences the problem that whenever the Influx database is down, yanic stalls completely and doesn't even write the meshviewer JSONs anymore. This leads to a completely red map and a little bit of elevated heart rate, despite the network still being up.
If InfluxDB is down, and the remote host doesn't respond to the connection attempt with Refused/Port Closed/whatever but just drops the packets, `conn.client.Write()` in the `addWorker` (and other places where InfluxDB is contacted) hangs infinitely. The default client config has no timeout (https://pkg.go.dev/github.com/influxdata/influxdb1-client/v2#HTTPConfig).
When `conn.points` fills up to `batchMaxSize`, `conn.addPoint()` and `conn.InsertPoint()` stop as well, which makes `coll.saveResponse()` stop as well, not …
=> [BUGFIX] Set timeout for InfluxDB HTTP client

contrib/yanic-import-timestamp
This fixes an issue when an import from other yanic is needed.
The datetime can have different timezones with yanic_date_format. The latest yanic format is now used as a fallback if the millisecond format from hopglass is not present.
fixes #220
=> [BUGFIX] yanic-import-timestamp: allow importing from other yanic instance

INSTALL.md, docs/docs/install.md
This adds a sentence on how to install the dev version, as the package complains when installed from other repos like `go install github.com/maurerle/yanic@install_dev` (as FreifunkBremen is mentioned everywhere and the package name does not match then)
=> chore(docs): add install instructions for dev install

database/influxdb/node.go
I think that the information if a node is a gateway should also be available in the influxdb:
is_gateway is more meaningful than "vpn"  - which is the variable where this comes from actually.
I think, that this is more useful as a tag to filter than as a field of the data.
I did not find a way to add a boolean tag in influxdb, so I am writing it as string. (ref: https://stackoverflow.com/a/56989192 )
=> feat(database/influxdb) add information if a node is a gateway to influxdb

database/influxdb/database.go, database/influxdb/database_test.go
Sanitize tag values before they are being sent to Influx.
This fixes issues where users use '\n' in tag values (e.g. the owner) that is incompatible with InfluxDB's Line protocol.'
Thanks a lot for @T0biii for the help in tracing this error and creating a solution!
We keep on seeing errors in the yanic log about
```
May 27 16:08:33 gw04.in.ffmuc.net yanic[4157917]: time="2024-05-27T16:08:33.759+02:00" level="error" msg="{\"error\":\"partial write: unable to parse 'node,...,owner=peter@hase': missing fields dropped=0\"}\n" caller="database.go:165 github.com/FreifunkBremen/yanic/database/influxdb.(*Connection).addWorker"
```
Because the user uses `peter@hase\n.de` as their owner name. This works in other parts of yanic, but causes issues with influx.
=> fix(database/influxdb): replace invisible chars and whitespaces with space

.gitignore, config_example.toml, data/nodeinfo.go, data/nodeinfo_test.go, data/testdata/nodeinfo.json, database/influxdb/global_test.go, database/influxdb/node.go, database/influxdb/node_test.go, database/influxdb2/node.go, output/geojson/geojson_test.go, output/meshviewer-ffrgb/struct.go, output/meshviewer-ffrgb/struct_test.go, output/meshviewer/nodes_test.go, output/nodelist/nodelist_test.go, output/raw-jsonl/raw_jsonl_test.go, output/raw/raw_test.go, runtime/stats_test.go
This adds support for the recently introduced OpenWrt Target Information in Gluon: https://github.com/freifunk-gluon/gluon/pull/3496
Mainly beeing able to tell which Subtarget an x86 system is part of (64, generic, geode or legacy).
=> feat(data): handle gluon target information

database/influxdb/link.go, database/influxdb/node_test.go, database/influxdb2/link.go, output/meshviewer-ffrgb/meshviewer.go, output/meshviewer-ffrgb/meshviewer_test.go, runtime/link.go, runtime/node.go, runtime/nodes.go, runtime/nodes_test.go
refactory runtime/link:
- move link type from meshviewer-ffrgb to runtime
- add link type to database influxdb and influxdb2
=> feat: link type everywhere
