FreifunkBremen/yanic

- config_example.yml
- jsontime/jsontime.go
- meshviewer/meshviewer.go
- models/config.go
- models/graph.go
- models/graph_test.go
- models/node.go
- models/nodes.go
- models/nodes_test.go
> Expire nodes after n days of inactivity

- database/database.go
- models/config.go
Node specific data should be remove from the InfluxDB after some days
> want to resolve #8:  Purge node specific statistics after several days

- meshviewer/meshviewer.go
- models/config.go
- models/nodes.go
- models/nodes_test.go
- models/stats_test.go
We want to support: https://github.com/ffrgb/meshviewer
> Export multiple versions of JSON for different Meshviewers

- data/statistics.go
- meshviewer/meshviewer.go
- models/node.go
- models/node_test.go
- models/nodes_test.go
- models/stats_test.go
For displaying diagrammes like the secound here: https://ffhb.de/map/node.html?id=66:6a:b3:8a:49:80
Neighbours count maybe seperate after:
* vpn
* physical
* ethernat
* wifi
* wifi 2.4 Ghz
* wifi 5 Ghz
> first implementation of neighbours count

- models/graph.go
Thought, i hat it solved in #22 :(
> [BUG] fix graph.json id

- models/graph.go
No locking in graph.go - it is a loop ...
Thought, i hat already solved it in #22 :(
> [BUGFIX] graph.go runs into deadlock

- meshviewer/meshviewer.go
> [BUGFIX] Memory calc for meshviewer

- models/node.go
Thank you to: lemoer <git@irrelefant.net>
https://paste.irrelefant.net/Liengie9.txt
> [TASK] Add model, firmware_base and firmware_relase tag to node statistics.

- cmd/yanic-query/main.go
- cmd/yanic/main.go
- config_example.toml
- models/config.go
- respond/collector.go
Hab nie darüber nachgedacht, das man dies brauchen könnte.
Könnte für firewalls interessante sein.
> [TASK] Allow binding to arbitrary ports for respondd querying

- .travis.yml
See https://docs.travis-ci.com/user/languages/go/#Specifying-a-Go-version-to-use
> Test more Go versions

- cmd/yanic-query/main.go
> [DOC] usage example comment (fix rename to yanic )

- cmd/yanic/main.go
- config_example.toml
- runtime/config.go
This could solve the missing data points issue as described in https://github.com/FreifunkBremen/yanic/pull/65#issuecomment-304801826 .
> Delay startup until a multiple of the period since zero time

- cmd/query.go
- cmd/serve.go
- config_example.toml
- respond/collector.go
- respond/collector_test.go
- respond/respond.go
- runtime/config.go
- runtime/config_test.go
- runtime/node.go
> [TASK] Add support for listening on multiple interfaces

- INSTALL.md
- config_example.toml
This is a stub, there are some open questions, what that should mean I marked with `???`
> [DOC] fix grammar in INSTALL.md and config_example.toml

- output/meshviewer-ffrgb/struct.go
- output/meshviewer-ffrgb/struct_test.go
> [BUGFIX] output meshviewer-ffrgb export owner

- .test-coverage
- .travis.yml
- README.md
- circle.yml
- output/all/internal_test.go
- output/internal_test.go
For all these, how is to lazy to build it on his own
> [TASK] use circle ci for build artifacts + enable data race detection

- database/influxdb/database.go
- database/influxdb/global.go
- database/influxdb/global_test.go
- database/influxdb/node.go
- database/influxdb/node_test.go
- runtime/stats.go
- runtime/stats_test.go
fixed #91 
@jplitza was hälst du davon? Ist es Sinnvoll als Tag am Measurement `node`?
> [TASK] add autoupdater to influxdb database

- output/all/filter.go
> [BUGFIX] write during map interation

- data/nodeinfo.go
- output/all/filter_inarea.go
- output/all/filter_inarea_test.go
- output/meshviewer-ffrgb/struct.go
- output/meshviewer-ffrgb/struct_test.go
- output/nodelist/nodelist.go
- output/nodelist/nodelist_test.go
Rename Longtitude to Longitude
> [BUGFIX] fix typo

- output/meshviewer-ffrgb/struct.go
- output/meshviewer/node.go
- output/meshviewer/nodes_v1.go
- output/meshviewer/nodes_v2.go
- output/nodelist/nodelist.go
In stats and state (cache) keep values, to view last stats for a flipping node
fixed #83 and https://github.com/ffrgb/meshviewer#231
> [TASK] show online clients in output if online

- LICENSE
- LICENSE.md
- README.md
Without license this software can not be used by any one except the authors.
We'll merge this at the first of january 2018 if nobody has any concerns.
> Add AGPL license

- circle.yml
- cmd/version.go
> [TASK] print version of git

- config_example.toml
- database/all/main.go
- database/respondd/main.go
- database/respondd/main_test.go
- docs/docs_configuration.md
fixed #118 
~~blocked by #104  (just usable if reciever could configurate interface)~~
> [TASK] database to forward respondd packets

- data/statistics.go
- database/influxdb/database.go
- database/influxdb/node.go
This requires my changes from:
* https://github.com/digineo/dnsmasq/compare/metrics
* https://github.com/ffnord/mesh-announce/compare/master...corny:dhcp
> [TASK] add DHCP statistics

- docs/docs_configuration.md
- respond/collector.go
> [TASK] improve autoselect ip_address of interfaces

- data/statistics.go
- database/influxdb/node.go
- database/influxdb/node_test.go
> [TASK] add procstat

- database/influxdb/database.go
- database/influxdb/database_test.go
- docs/docs_configuration.md
> [TASK] allow self-signed certification in influxdb

- data/statistics.go
- database/graphite/node.go
- database/influxdb/node.go
- output/meshviewer-ffrgb/struct.go
- output/meshviewer/node.go
Fix memory usage estimation following this commit:
https://github.com/freifunk-gluon/gluon/pull/1517
Follow gluon
> [BUGFIX] use available memory for usage estimation

- output/meshviewer-ffrgb/meshviewer.go
- output/meshviewer-ffrgb/meshviewer_test.go
> [BUGFIX] show NaN on link

- cmd/config.go
- cmd/import.go
- cmd/query.go
- cmd/root.go
- cmd/serve.go
- database/all/connection.go
- database/graphite/database.go
- database/influxdb/database.go
- database/logging/file.go
- database/respondd/main.go
- main.go
- output/all/output.go
- output/filter/filter.go
- output/meshviewer-ffrgb/meshviewer.go
- output/meshviewer/output.go
- respond/collector.go
- rrd/rrd.go
- runtime/nodes.go
- runtime/nodes_test.go
- webserver/webserver.go
> [TASK] improve logging

- config_example.toml
- docs/docs_configuration.md
- output/all/filter.go
- output/all/output_test.go
- output/filter/blocklist/blocklist.go
- output/filter/blocklist/blocklist_test.go
it contains breaking changes in the config files
> black lives matter

- data/nodeinfo.go
- database/influxdb/global_test.go
- database/influxdb/node.go
- database/influxdb/node_test.go
- output/geojson/geojson.go
- output/geojson/geojson_test.go
- output/meshviewer-ffrgb/struct.go
- output/meshviewer-ffrgb/struct_test.go
- output/meshviewer/nodes_test.go
- output/nodelist/nodelist_test.go
- output/raw/raw_test.go
- runtime/stats.go
- runtime/stats_test.go
> [BUGFIX] nodeinfo without empty values

- README.md
- docs/home_running.md
This briefly describes how we use yanic in hanover.
This does not fix any problems, other than promoting yanic a little more.
> [DOC] mention Freifunk Hannover

- README.md
- docs/home_running.md
This implements the proposed changes by @cmarxmeier and resolves #159.
Careful, his original proposal wanted to link to a now removed github repo.
> **Freifunk Rhein-Sieg e.V** [...] - see [Github](https://github.com/Freifunk-Rhein-Sieg/Ansible-Freifunk-Gateway)
I just wanted to clean up the stalled issue to get a better overview.
> [DOC] Mention community Freifunk Rhein-Sieg e.V.

- README.md
> Readme: Add Ingolstadt to user list

- output/prometheus-sd/output.go
- output/prometheus-sd/output_test.go
> feat(output/prometheus-sd): improve and add labels

- README.md
This adds Freifunk Aachen ([FFAC](https://github.com/ffac/)) to the list of communities using this project
> [DOC] add ffac to description

- database/influxdb/database.go
> fix(database/influxdb): typo log messages

- .github/workflows/go.yml
> fix(ci): build and release binary

- config_example.toml
- database/logging/file.go
- database/logging/file_test.go
- docs/docs/configuration.md
make logs serializable and first tries of `log/slog` (see #229 )
> fix(database/logging): refactory to use slog
